package com.serviceops.inventory.application;

import com.serviceops.common.application.CsvFileService;
import com.serviceops.inventory.web.InventoryDtos.SparePartResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class InventoryCsvService {
    private static final List<String> SPARE_PART_HEADERS = List.of(
            "Tên phụ tùng", "Đơn vị", "Tồn ban đầu", "Ngưỡng tồn tối thiểu", "Đơn giá", "Hoạt động"
    );
    private static final List<String> PREVIOUS_SPARE_PART_HEADERS = List.of(
            "Mã phụ tùng", "Tên phụ tùng", "Đơn vị", "Tồn ban đầu", "Ngưỡng tồn tối thiểu", "Đơn giá", "Hoạt động"
    );
    private static final List<String> LEGACY_SPARE_PART_HEADERS = List.of(
            "sku", "name", "unit", "initialStock", "reorderLevel", "unitPrice", "active"
    );
    private final CsvFileService csvFileService;

    public List<SparePartCsvRow> parseSpareParts(MultipartFile file) {
        return csvFileService.parseAny(
                        file,
                        List.of(SPARE_PART_HEADERS, PREVIOUS_SPARE_PART_HEADERS, LEGACY_SPARE_PART_HEADERS),
                        "kho phụ tùng"
                )
                .stream()
                .map(row -> toRow(row.rowNumber(), row.values()))
                .toList();
    }

    public byte[] sparePartTemplate() {
        return csvFileService.write(List.of(
                SPARE_PART_HEADERS,
                List.of("Lưới lọc máy lạnh", "cái", "10", "3", "95000", "Có")
        ));
    }

    public byte[] exportSpareParts(List<SparePartResponse> parts) {
        List<List<String>> rows = new ArrayList<>();
        rows.add(List.of("Mã phụ tùng", "Tên phụ tùng", "Đơn vị", "Tồn hiện tại", "Ngưỡng tồn tối thiểu", "Đơn giá", "Sắp hết hàng", "Hoạt động", "Ngày cập nhật"));
        for (SparePartResponse part : parts) {
            rows.add(List.of(
                    part.sku(),
                    part.name(),
                    part.unit(),
                    format(part.stockQuantity()),
                    format(part.reorderLevel()),
                    format(part.unitPrice()),
                    part.lowStock() ? "Có" : "Không",
                    part.active() ? "Có" : "Không",
                    part.updatedAt() == null ? "" : part.updatedAt().toString()
            ));
        }
        return csvFileService.write(rows);
    }

    private static SparePartCsvRow toRow(int rowNumber, List<String> values) {
        boolean previousFormat = values.size() >= PREVIOUS_SPARE_PART_HEADERS.size();
        int offset = previousFormat ? 1 : 0;
        return new SparePartCsvRow(
                rowNumber,
                previousFormat ? value(values, 0) : "",
                value(values, offset),
                value(values, offset + 1),
                value(values, offset + 2),
                value(values, offset + 3),
                value(values, offset + 4),
                value(values, offset + 5)
        );
    }

    private static String value(List<String> values, int index) {
        return index < values.size() ? values.get(index).trim() : "";
    }

    private static String format(BigDecimal value) {
        return value == null ? "0" : value.stripTrailingZeros().toPlainString();
    }

    /** sourceSku is retained only to accept older CSV files; new business codes are always generated by the backend. */
    public record SparePartCsvRow(
            int rowNumber,
            String sourceSku,
            String name,
            String unit,
            String initialStock,
            String reorderLevel,
            String unitPrice,
            String active
    ) {
        public String sku() {
            return sourceSku;
        }
    }
}
