package com.serviceops.customer.application;

import com.serviceops.common.application.CsvFileService;
import com.serviceops.customer.web.CustomerDtos.CustomerResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.util.ArrayList;
import java.util.List;

@Service
@RequiredArgsConstructor
public class CustomerCsvService {
    private static final List<String> CUSTOMER_HEADERS = List.of(
            "Tên khách hàng", "Điện thoại", "Email", "Địa chỉ", "Ghi chú", "Hoạt động"
    );
    private static final List<String> PREVIOUS_CUSTOMER_HEADERS = List.of(
            "Mã khách hàng", "Tên khách hàng", "Điện thoại", "Email", "Địa chỉ", "Ghi chú", "Hoạt động"
    );
    private static final List<String> LEGACY_CUSTOMER_HEADERS = List.of(
            "code", "name", "phone", "email", "address", "notes", "active"
    );

    private final CsvFileService csvFileService;

    public List<CustomerCsvRow> parseCustomers(MultipartFile file) {
        return csvFileService.parseAny(
                        file,
                        List.of(CUSTOMER_HEADERS, PREVIOUS_CUSTOMER_HEADERS, LEGACY_CUSTOMER_HEADERS),
                        "khách hàng"
                )
                .stream()
                .map(row -> toRow(row.rowNumber(), row.values()))
                .toList();
    }

    public byte[] customerTemplate() {
        return csvFileService.write(List.of(
                CUSTOMER_HEADERS,
                List.of("Công ty Minh Anh", "0909123456", "support@example.com", "12 Nguyễn Trãi, TP.HCM", "Khách hàng bảo trì định kỳ", "Có")
        ));
    }

    public byte[] exportCustomers(List<CustomerResponse> customers) {
        List<List<String>> rows = new ArrayList<>();
        rows.add(List.of("Mã khách hàng", "Tên khách hàng", "Điện thoại", "Email", "Địa chỉ", "Ghi chú", "Hoạt động", "Ngày tạo", "Ngày cập nhật"));
        for (CustomerResponse customer : customers) {
            rows.add(List.of(
                    cell(customer.code()),
                    cell(customer.name()),
                    cell(customer.phone()),
                    cell(customer.email()),
                    cell(customer.address()),
                    cell(customer.notes()),
                    customer.active() ? "Có" : "Không",
                    customer.createdAt() == null ? "" : customer.createdAt().toString(),
                    customer.updatedAt() == null ? "" : customer.updatedAt().toString()
            ));
        }
        return csvFileService.write(rows);
    }

    private static CustomerCsvRow toRow(int rowNumber, List<String> values) {
        boolean previousFormat = values.size() >= PREVIOUS_CUSTOMER_HEADERS.size();
        int offset = previousFormat ? 1 : 0;
        return new CustomerCsvRow(
                rowNumber,
                previousFormat ? value(values, 0) : "",
                value(values, offset),
                value(values, offset + 1),
                value(values, offset + 2),
                value(values, offset + 3),
                value(values, offset + 4),
                value(values, offset + 5)
        );
    }

    private static String value(List<String> values, int index) {
        return index < values.size() ? values.get(index).trim() : "";
    }

    private static String cell(String value) {
        return value == null ? "" : value;
    }

    /** sourceCode is retained only to accept older CSV files; new business codes are always generated by the backend. */
    public record CustomerCsvRow(
            int rowNumber,
            String sourceCode,
            String name,
            String phone,
            String email,
            String address,
            String notes,
            String active
    ) {
        public String code() {
            return sourceCode;
        }
    }
}
